// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: group.proto

package client

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _group_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on FindStudentsInGroupRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FindStudentsInGroupRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FindStudentsInGroupRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FindStudentsInGroupRequestMultiError, or nil if none found.
func (m *FindStudentsInGroupRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *FindStudentsInGroupRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetGroupId()); err != nil {
		err = FindStudentsInGroupRequestValidationError{
			field:  "GroupId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return FindStudentsInGroupRequestMultiError(errors)
	}

	return nil
}

func (m *FindStudentsInGroupRequest) _validateUuid(uuid string) error {
	if matched := _group_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// FindStudentsInGroupRequestMultiError is an error wrapping multiple
// validation errors returned by FindStudentsInGroupRequest.ValidateAll() if
// the designated constraints aren't met.
type FindStudentsInGroupRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FindStudentsInGroupRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FindStudentsInGroupRequestMultiError) AllErrors() []error { return m }

// FindStudentsInGroupRequestValidationError is the validation error returned
// by FindStudentsInGroupRequest.Validate if the designated constraints aren't met.
type FindStudentsInGroupRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FindStudentsInGroupRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FindStudentsInGroupRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FindStudentsInGroupRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FindStudentsInGroupRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FindStudentsInGroupRequestValidationError) ErrorName() string {
	return "FindStudentsInGroupRequestValidationError"
}

// Error satisfies the builtin error interface
func (e FindStudentsInGroupRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFindStudentsInGroupRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FindStudentsInGroupRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FindStudentsInGroupRequestValidationError{}

// Validate checks the field values on FindStudentsInGroupResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FindStudentsInGroupResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FindStudentsInGroupResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FindStudentsInGroupResponseMultiError, or nil if none found.
func (m *FindStudentsInGroupResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *FindStudentsInGroupResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetStudentsInGroup() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, FindStudentsInGroupResponseValidationError{
						field:  fmt.Sprintf("StudentsInGroup[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, FindStudentsInGroupResponseValidationError{
						field:  fmt.Sprintf("StudentsInGroup[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return FindStudentsInGroupResponseValidationError{
					field:  fmt.Sprintf("StudentsInGroup[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return FindStudentsInGroupResponseMultiError(errors)
	}

	return nil
}

// FindStudentsInGroupResponseMultiError is an error wrapping multiple
// validation errors returned by FindStudentsInGroupResponse.ValidateAll() if
// the designated constraints aren't met.
type FindStudentsInGroupResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FindStudentsInGroupResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FindStudentsInGroupResponseMultiError) AllErrors() []error { return m }

// FindStudentsInGroupResponseValidationError is the validation error returned
// by FindStudentsInGroupResponse.Validate if the designated constraints
// aren't met.
type FindStudentsInGroupResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FindStudentsInGroupResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FindStudentsInGroupResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FindStudentsInGroupResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FindStudentsInGroupResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FindStudentsInGroupResponseValidationError) ErrorName() string {
	return "FindStudentsInGroupResponseValidationError"
}

// Error satisfies the builtin error interface
func (e FindStudentsInGroupResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFindStudentsInGroupResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FindStudentsInGroupResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FindStudentsInGroupResponseValidationError{}
