// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: student.proto

package client

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on StudentFindByUsernameRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *StudentFindByUsernameRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StudentFindByUsernameRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StudentFindByUsernameRequestMultiError, or nil if none found.
func (m *StudentFindByUsernameRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *StudentFindByUsernameRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetStudentUsername()); l < 4 || l > 30 {
		err := StudentFindByUsernameRequestValidationError{
			field:  "StudentUsername",
			reason: "value length must be between 4 and 30 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return StudentFindByUsernameRequestMultiError(errors)
	}

	return nil
}

// StudentFindByUsernameRequestMultiError is an error wrapping multiple
// validation errors returned by StudentFindByUsernameRequest.ValidateAll() if
// the designated constraints aren't met.
type StudentFindByUsernameRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StudentFindByUsernameRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StudentFindByUsernameRequestMultiError) AllErrors() []error { return m }

// StudentFindByUsernameRequestValidationError is the validation error returned
// by StudentFindByUsernameRequest.Validate if the designated constraints
// aren't met.
type StudentFindByUsernameRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StudentFindByUsernameRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StudentFindByUsernameRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StudentFindByUsernameRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StudentFindByUsernameRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StudentFindByUsernameRequestValidationError) ErrorName() string {
	return "StudentFindByUsernameRequestValidationError"
}

// Error satisfies the builtin error interface
func (e StudentFindByUsernameRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStudentFindByUsernameRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StudentFindByUsernameRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StudentFindByUsernameRequestValidationError{}

// Validate checks the field values on StudentFindByUsernameResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *StudentFindByUsernameResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StudentFindByUsernameResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// StudentFindByUsernameResponseMultiError, or nil if none found.
func (m *StudentFindByUsernameResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *StudentFindByUsernameResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetStudent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, StudentFindByUsernameResponseValidationError{
					field:  "Student",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, StudentFindByUsernameResponseValidationError{
					field:  "Student",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStudent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return StudentFindByUsernameResponseValidationError{
				field:  "Student",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return StudentFindByUsernameResponseMultiError(errors)
	}

	return nil
}

// StudentFindByUsernameResponseMultiError is an error wrapping multiple
// validation errors returned by StudentFindByUsernameResponse.ValidateAll()
// if the designated constraints aren't met.
type StudentFindByUsernameResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StudentFindByUsernameResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StudentFindByUsernameResponseMultiError) AllErrors() []error { return m }

// StudentFindByUsernameResponseValidationError is the validation error
// returned by StudentFindByUsernameResponse.Validate if the designated
// constraints aren't met.
type StudentFindByUsernameResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StudentFindByUsernameResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StudentFindByUsernameResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StudentFindByUsernameResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StudentFindByUsernameResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StudentFindByUsernameResponseValidationError) ErrorName() string {
	return "StudentFindByUsernameResponseValidationError"
}

// Error satisfies the builtin error interface
func (e StudentFindByUsernameResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStudentFindByUsernameResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StudentFindByUsernameResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StudentFindByUsernameResponseValidationError{}
