// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: student.proto

package client

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _student_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on StudentFindByIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *StudentFindByIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StudentFindByIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StudentFindByIDRequestMultiError, or nil if none found.
func (m *StudentFindByIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *StudentFindByIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetStudentId()); err != nil {
		err = StudentFindByIDRequestValidationError{
			field:  "StudentId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return StudentFindByIDRequestMultiError(errors)
	}

	return nil
}

func (m *StudentFindByIDRequest) _validateUuid(uuid string) error {
	if matched := _student_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// StudentFindByIDRequestMultiError is an error wrapping multiple validation
// errors returned by StudentFindByIDRequest.ValidateAll() if the designated
// constraints aren't met.
type StudentFindByIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StudentFindByIDRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StudentFindByIDRequestMultiError) AllErrors() []error { return m }

// StudentFindByIDRequestValidationError is the validation error returned by
// StudentFindByIDRequest.Validate if the designated constraints aren't met.
type StudentFindByIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StudentFindByIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StudentFindByIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StudentFindByIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StudentFindByIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StudentFindByIDRequestValidationError) ErrorName() string {
	return "StudentFindByIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e StudentFindByIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStudentFindByIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StudentFindByIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StudentFindByIDRequestValidationError{}

// Validate checks the field values on StudentFindByIDResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *StudentFindByIDResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StudentFindByIDResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StudentFindByIDResponseMultiError, or nil if none found.
func (m *StudentFindByIDResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *StudentFindByIDResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetStudent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, StudentFindByIDResponseValidationError{
					field:  "Student",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, StudentFindByIDResponseValidationError{
					field:  "Student",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStudent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return StudentFindByIDResponseValidationError{
				field:  "Student",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return StudentFindByIDResponseMultiError(errors)
	}

	return nil
}

// StudentFindByIDResponseMultiError is an error wrapping multiple validation
// errors returned by StudentFindByIDResponse.ValidateAll() if the designated
// constraints aren't met.
type StudentFindByIDResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StudentFindByIDResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StudentFindByIDResponseMultiError) AllErrors() []error { return m }

// StudentFindByIDResponseValidationError is the validation error returned by
// StudentFindByIDResponse.Validate if the designated constraints aren't met.
type StudentFindByIDResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StudentFindByIDResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StudentFindByIDResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StudentFindByIDResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StudentFindByIDResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StudentFindByIDResponseValidationError) ErrorName() string {
	return "StudentFindByIDResponseValidationError"
}

// Error satisfies the builtin error interface
func (e StudentFindByIDResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStudentFindByIDResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StudentFindByIDResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StudentFindByIDResponseValidationError{}
