// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: teacher.proto

package client

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _teacher_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on TeacherFindByIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TeacherFindByIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TeacherFindByIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TeacherFindByIDRequestMultiError, or nil if none found.
func (m *TeacherFindByIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TeacherFindByIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetTeacherId()); err != nil {
		err = TeacherFindByIDRequestValidationError{
			field:  "TeacherId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return TeacherFindByIDRequestMultiError(errors)
	}

	return nil
}

func (m *TeacherFindByIDRequest) _validateUuid(uuid string) error {
	if matched := _teacher_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// TeacherFindByIDRequestMultiError is an error wrapping multiple validation
// errors returned by TeacherFindByIDRequest.ValidateAll() if the designated
// constraints aren't met.
type TeacherFindByIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TeacherFindByIDRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TeacherFindByIDRequestMultiError) AllErrors() []error { return m }

// TeacherFindByIDRequestValidationError is the validation error returned by
// TeacherFindByIDRequest.Validate if the designated constraints aren't met.
type TeacherFindByIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TeacherFindByIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TeacherFindByIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TeacherFindByIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TeacherFindByIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TeacherFindByIDRequestValidationError) ErrorName() string {
	return "TeacherFindByIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e TeacherFindByIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTeacherFindByIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TeacherFindByIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TeacherFindByIDRequestValidationError{}

// Validate checks the field values on TeacherFindByIDResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TeacherFindByIDResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TeacherFindByIDResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TeacherFindByIDResponseMultiError, or nil if none found.
func (m *TeacherFindByIDResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *TeacherFindByIDResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTeacher()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TeacherFindByIDResponseValidationError{
					field:  "Teacher",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TeacherFindByIDResponseValidationError{
					field:  "Teacher",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTeacher()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TeacherFindByIDResponseValidationError{
				field:  "Teacher",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return TeacherFindByIDResponseMultiError(errors)
	}

	return nil
}

// TeacherFindByIDResponseMultiError is an error wrapping multiple validation
// errors returned by TeacherFindByIDResponse.ValidateAll() if the designated
// constraints aren't met.
type TeacherFindByIDResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TeacherFindByIDResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TeacherFindByIDResponseMultiError) AllErrors() []error { return m }

// TeacherFindByIDResponseValidationError is the validation error returned by
// TeacherFindByIDResponse.Validate if the designated constraints aren't met.
type TeacherFindByIDResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TeacherFindByIDResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TeacherFindByIDResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TeacherFindByIDResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TeacherFindByIDResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TeacherFindByIDResponseValidationError) ErrorName() string {
	return "TeacherFindByIDResponseValidationError"
}

// Error satisfies the builtin error interface
func (e TeacherFindByIDResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTeacherFindByIDResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TeacherFindByIDResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TeacherFindByIDResponseValidationError{}
